FROM python:3.11-slim

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /usr/src/app

# install dependencies
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include the src directory
ENV PYTHONPATH=/usr/src/app/src

# copy src code
COPY ./src ./src

EXPOSE 4000

# FASTAPI / STREAMLIT
ENTRYPOINT ["streamlit", "run", "src/app.py", "--server.port=4000", "--server.address=0.0.0.0"]